### ISSUE TITLE
Continue interrupted builds

### ISSUE THREAD

**Issue by bennyz** [nirs/oci#28]
In case our process crashed somehow (computer powered off or whatever), it should be made possible to continue where we left off since the job keeps running on jenkins.

Open questions:
How do we save the state? Is a simple json file enough? Do we need something more robust?
What should we save?
Probably change number, build number, current "step"

**Comment by nirs** [comment]
First we should think about the user experience.

Here is possible flow:
```
$ oci system-tests 12345
...
[ 7/8 ] Waiting until job is finished
        job: https://jenkins.ovirt.org/job/ovirt-system-tests_manual/87654
```
-- POWER LOST --

Query interrupted jobs:
```
$ oci jobs
1   build-artifacts 
    change: 12345 project: vdsm branch: ovirt-4.3 patchset: 7 
    job: https://jenkins.ovirt.org/job/ovirt-system-tests_manual/87654
```
Continue interrupted jobs:
```
$ oci continue 1
[ 7/8 ] Waiting until job is finished
        job: https://jenkins.ovirt.org/job/ovirt-system-tests_manual/87654
[ 8/8 ] Job completed successfully!
```

Completed job deleted:
```
$ oci jobs
(nothing)
```

Regarding implementation:
- json file per job sounds like good idea. For robustness we can use atomic write:
  see https://gerrit.ovirt.org/c/96438/
- store new json each time step starts, replacing old json
- store all the info we collected about the job during the build. The only detail which may not be helpful is the queue item id, since the item disappear after couple of minutes.
