### ISSUE TITLE
Email the results

### ISSUE THREAD

**Issue by didib** [nirs/oci#49]
Would be nice to get the build results in email, so that you can "launch and forget" and do not have to remember to check it until it finishes.

I think it's enough, as a start, to assume that sending is "trivial" - using the local machine sendmail - and just add to the configuration an email address to send to. Later we can add support for directly sending to remote servers, authentication, etc., if/when needed.

Perhaps we even want multiple emails - build job started/finished, OST job started/finished. Perhaps use the same subject for all, but with something unique (e.g. the change ID or even subject) to easily find them in one's mailbox.

I still didn't try using this project, intend to soon, and this issue will probably be the first one I'll work on, unless someone takes over...

**Comment by nirs** [comment]
This is a command line tool, running on your machine. Why do you need to send email to 
yourself when the command completes?

On my machine (Fedora 32), Gnome shows a notification when a terminal commands ends.
This feature sounds like better match for a server, when want to track multiple jobs.

Or as separate tool reporting the result and output of a command by email:

    send-email command args...

Or showing desktop notifications:

    send-notification command args...

Such tool can work with any command, instead of adding the capability to all long running
commands.

If we want builtin notifications, Integrating with notify-send sounds more useful.
