### ISSUE TITLE
Add check-patch sub command

### ISSUE THREAD

**Issue by nirs** [nirs/oci#9]
Example usage:

     oci check-patch CHANGE_NUMBER

The command should start check-patch stage using jenkins.run() for the specified change and watch the job until it completes.

**Comment by bell-lev** [comment]
@nir I think it is a good idea to combine the check-patch and the build-artifacts. They are both in the "stage type" category, and the more stages we add (check-networks or other custom stages, the more sub_parsers we will have.

I think it is better to be able to run something like:
`ovirt-ci --stage check-patch CHANGE_NUMBER`
or
`ovirt-ci --stage build-artifacts CHANGE_NUMBER`
because then we will have just one function that deals with any stage, custom or not.

What do you think?

**Comment by nirs** [comment]
Having to type --stage is annoying. We want a command for the standard stages.
The implementation can be shared, the user should care about this.

To run custom stage, we have:

    ovirt-ci run check-network 12345

See #10
